### PR TITLE
Fixes for Apple and Android assets and metadata

### LINKED ISSUE #12: tvOS app icon 800x480 missing or incorrect dimensions
I used version 0.0.6 with all icons of correct sizes mentioned in README for tvOS. While trying to upload to TestFlight, the analysis returns error with 
_"Asset validation Failed - Invalid Image Asset. The image stack 'App Icon' in 'Payload/ProjectName/Assets.car' has a background image that does not match the canvas dimensions '800x480'._

Apple tvOS icon size [guide](https://developer.apple.com/design/human-interface-guidelines/app-icons#tvOS-app-icon-sizes) mentions having 2x version for Home Screen (800x480) as well as 1x (400x240).

### LINKED ISSUE #13: Android TV AndroidManifest feature update
Although this plugin will work as expected in Android TV, app will get rejected by Android Play Store with the error message _"Your app uses android.hardware.faketouch that are not available on Android TV."_

Android official website [guide](https://developer.android.com/training/tv/start/start#leanback-req) for Android TV says to make the change in AndroidManifest for feature _"android.hardware.touchscreen"_ and _"android.software.leanback"_ added as _android:required="false"_. 

What worked for me is to make these two features as well as _"android.hardware.faketouch"_ to be not required [(link)](https://developer.android.com/training/tv/start/hardware#declare-hardware-requirements)
You can take a look at my custom build file [withTVAndroidFeature.js](https://github.com/raymon-io/config-tv/blob/master/build/withTVAndroidFeature.js)
It would be helpful if you modify AndroidManifest for Android TV with these changes in the next update.

### PR DESCRIPTION
**Pull request by douglowder**
- Fix for `SDKROOT` value in Apple TV Xcode projects
- Restructure Apple TV brand asset catalog to include small icon at 2x size
  - See https://forums.solar2d.com/t/error-itms-90709-on-submission/347599/7 
- Add required touchscreen feature metadata for Android TV

Fixes #12 
Fixes #13

### CODE REVIEW

**Comment by douglowder** [comment]
@raymon-io please review this. If desired, I can publish a beta release for you to test these fixes.

**Comment by raymon-io** [comment]
Thank you, I will look into this very soon.

**Comment by raymon-io** [comment]
For Android TV this pull request works. tvOS also works after adding `iconSmall2x` in `app.json` file. You may need to update the README file which should mention `iconSmall2x`. 
However I forgot to mention in my issue that tvOS also encounters one last problem while uploading to TestFlight. That is
 `The key UIRequiredDeviceCapabilities in the Info.plist may not contain values that would prevent this application from running on any device.` 
To fix this issue I simply added this inside `app.json` 
```
"ios": {
      "infoPlist": {
        "UIRequiredDeviceCapabilities": [
          "arm64"
        ]
      }
    },
```
I don't know if you want to mention this inside README file or edit the Info.Plist using expo config plugin. 
I tested using local build so beta release is not necessary but if you do not want to release this change right away you and test more then you can create a beta release.
So far, all changes for this pull request works and approving in my review.

**Review by raymon-io — APPROVED** [review]

**Comment by douglowder** [comment]
Thanks @raymon-io I added a config plugin to take care of the UIRequiredDeviceCapabilities issue.

**Comment by arosemena** [comment]
Any reason leanback was forced set to false in this pr? the play store is rejecting a tv app because of this :(

image

**Comment by douglowder** [comment]
> Any reason leanback was forced set to false in this pr? the play store is rejecting a tv app because of this 

@arosemena another developer was seeing rejections for their app if this was not done. See #13 .

**Comment by raymon-io** [comment]
There is two different scenarios.
In first scenario when both mobile and tv tracks (in Google Play Store) are the same then this version will work. 
But when tv track and mobile tracks are different then this config will fail as the tv track will require the leanback feature to be set as true (not false). I think most people would want the tracks to be separate so I think for now you can change the feature into [true](https://github.com/react-native-tvos/config-tv/blob/main/packages/config-tv/src/withTVAndroidManifest.ts#L193).

**Comment by raymon-io** [comment]
Or another suggestion is to make it a variable for the user to choose in `app.json` file

**Pull request merged**
